### ISSUE TITLE
Licence du site vs Licence du contenu du site

### ISSUE THREAD

**Issue by fabienwang** [mozfr/www#109]
Plop,

sur le site je vois dans le pied de page: 
«Sauf mention contraire, le site est placé sous licence Creative Commons paternité partage à l'identique»

Il y a ambiguïté si cela concerne le site (dont ce dépot n'a d'ailleurs pas de fichier Licence ni de mention sur le site comme étant libre ou open-source)
ou bien si cette licence CC-BY-SA 3.0 concerne uniquement le contenu ?

merci, à bon entendeur salut ! :smile:

**Comment by MatonAnthony** [comment]
Je pense qu'il s'agit de la licence du contenu, mais à vrai dire j'en sais trop rien.
@pascalchevrel @TheoChevalier ?

**Comment by TheoChevalier** [comment]
Normalement oui, ça s’applique juste au contenu. Pour le code je dirais qu’un fichier similaire à https://github.com/mozfr/transvision/blob/master/LICENSE devrait suffire
