### ISSUE TITLE
retirer la majuscule à l'adjectif francophone

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/www#147]
« Mozilla Francophone » ou « communauté Mozilla Francophone » sont écrits dans mozfr.org (dans le title aussi) avec la majuscule bien qu'ils soient des adjectifs qui ne devraient pas prendre la majuscule.

**Comment by pascalchevrel** [comment]
corrigé

**Comment by Mozinet-fr** [comment]
Il reste une occurrence dans le title

**Comment by pascalchevrel** [comment]
Corrigé partout avec la PR#153
