### ISSUE TITLE
Ajout compte twitter

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/www#157]
Il faudrait avoir un lien vers notre compte twitter https://twitter.com/mozilla_fr

**Comment by Mozinet-fr** [comment]
et les meta Twitter dans le head des fichiers HTML.

**Comment by Mozinet-fr** [comment]
https://blog.mozfr.org/pages/Nos-reseaux-sociaux

**Comment by pascalchevrel** [comment]
Les métadonnées sont là mais je n'arrive pas à ce que le validateur de twitter extraie une image d'illustration à la carte. Je vais laisser le ticket ouvert pour le moment.

**Comment by Mozinet-fr** [comment]
Tu as forcé le cache ? https://cards-dev.twitter.com/validator

**Comment by TheoChevalier** [comment]
Il doit vouloir une URL absolue, pas relative. Facebook râle sur l’URL, mais finit quand même par trouver l’image
`Invalid URL
Provided og:image URL, /img/communityPicture.png was not a valid URL.`

**Comment by pascalchevrel** [comment]
> Il doit vouloir une URL absolue, pas relative. Facebook râle sur l’URL, mais finit quand même par trouver l’image
> `Invalid URL Provided og:image URL, /img/communityPicture.png was not a valid URL.`

Bien vu :) ça marche maintenant
