### ISSUE TITLE
Liens vers nos blog

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/www#158]
Probablement dans le footer comme ils font sur mozilla.org, on pourrait mettre des liens vers tous nos sites dont les blogs.

**Comment by lhirlimann** [comment]
Y a encore de l'activité firefox OS ?

**Comment by pascalchevrel** [comment]
> Y a encore de l'activité firefox OS ?
Pas à ma connaissance

**Comment by Mozinet-fr** [comment]
Normalement, on a veillé à tout archiver.

**Comment by Mozinet-fr** [comment]
Sur le blog :

![2019-07-03 18_11_35-gauche_Communauté Mozilla francophone](https://user-images.githubusercontent.com/8845401/60607815-56602780-9dbe-11e9-8320-3dcae54de977.png)

**Comment by pascalchevrel** [comment]
implémenté par le nouveau pied de page.
