### ISSUE TITLE
Erreurs dans pied de page

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/www#170]
Articles et réseaux sociaux (je serais plus pour mettre Blog principal et Blog technique)

Articles généraux : pas joli et peu engageant
Article techniques : manque un s
Mozilla et la vie publique
Suivez-nous sur twitter : majuscule

Manque Mastodon (on a quand même 1719 abonné·e·s)

Logiciels

Firefox : c'est voulu que le téléchargement commence directement ? Si oui faudrait le signaler.
Pré-versions de Firefox => Préversions
« Fenix » (Firefox Preview Android) => Personne ne connait Fenix, Firefox Preview suffirait
Thunderbird
Lockwise => les noms officiels sont Firefox Lockwise…
Send : idem
Monitor : idem

À propos

Le manifeste de Mozilla
Participer
Traduire
Forums et assistance
Documentation d'équipe : il faudrait que le mot wiki apparaisse, pour beaucoup c'est plus parlant (aussi apostrophe non typographique)

**Comment by pascalchevrel** [comment]
> Firefox : c'est voulu que le téléchargement commence directement ? Si oui faudrait le signaler.

Oui c'est voulu, c'est un lien appelé "Télécharger", c'est explicite, je ne vois pas ce qu'il y a à signaler

**Comment by Mozinet-fr** [comment]
![2019-07-04 19_59_32-gauche_Mozilla francophone - Communauté Mozilla francophone](https://user-images.githubusercontent.com/8845401/60683132-6fd4a280-9e96-11e9-852b-4805ef2389af.png)

j'ai pas de Télécharger

**Comment by pascalchevrel** [comment]
je pense avoir tout corrigé.
