### ISSUE TITLE
Nouveau logo mozfr sans la francophonie ?

### ISSUE THREAD

**Issue by dattaz** [mozfr/www#187]
Hello,

Avant on avait notre mascotte, avec sa queue au couleur de la francophie, si je comprend la volonté d'armoniser et d'avoir un logo proche de celui de mozilla, je trouve dommage de perdre cette référence.

Toujours est-il voici une proposition (clairement pas ouf ouf...)
![Screenshot_2019-07-08 Communauté Mozilla francophone](https://user-images.githubusercontent.com/6572195/60829985-82ace700-a1b6-11e9-8433-35fa1a271f8a.png)

Ci-joint le code HTML à l'arrache ;) :
```
<a href="/" title="Mozilla francophone" class="mozfrtext">
  <span style="text-decoration: underline;text-decoration-color: red;color: white;font-style: initial;font-weight: bold;">m</span>
  <span style="text-decoration: underline;text-decoration-color: deepskyblue;color: white;font-style: initial;font-weight: bold;">o</span>
  <span style="text-decoration: underline;text-decoration-color: yellow;color: white;font-style: initial;font-weight: bold;">z</span>
  <span style="text-decoration: underline;text-decoration-color: green;">f</span>
  <span style="text-decoration: underline;text-decoration-color: purple;">r</span>
</a>
```

**Comment by pascalchevrel** [comment]
fait
