### ISSUE TITLE
Chevauchement des titres longs de la page Participer sur le petit écran de Firefox OS

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/www#68]
Dans mon Firefox OS (ZTE Open C) les titres de plusieurs mots de la page Participer se chevauchent :

![Page Participer](http://blogzinet.free.fr/images/2015-03-02-10-12-07_participer.png)

**Comment by pandark** [comment]
https://github.com/mozfr/www/blob/master/custom/views/default/static-pages.tpl.php#L26

**Comment by fabienwang** [comment]
![after_commit](https://cloud.githubusercontent.com/assets/8741873/11852159/cc6ae9d6-a436-11e5-8c40-da97be72515d.png)

Corrigé, on peut donc intégrer pull-request
