### ISSUE TITLE
Lien vers l'apk de Firefox pour Android cassé.

### ISSUE THREAD

**Issue by Flaburgan** [mozfr/www#71]

**Comment by TheoChevalier** [comment]
Bien vu. La question est maintenant lequel de ces liens on expose. Uniquement api 11 qui semble être la version la plus répandue, ou on modifie un peu la page pour les afficher tous les trois sans que ça fasse trop lourd visuellement ?

https://ftp.mozilla.org/pub/mozilla.org/mobile/releases/latest/android-api-9/fr/
https://ftp.mozilla.org/pub/mozilla.org/mobile/releases/latest/android-api-11/fr/
https://ftp.mozilla.org/pub/mozilla.org/mobile/releases/latest/android-x86/multi/fennec-39.0.multi.android-i386.apk

**Comment by TheoChevalier** [comment]
Cette page vient d'être créée et semble régler le problème : https://www.mozilla.org/en-US/firefox/android/all/
