### ISSUE TITLE
Mise en place d'une bannière de soutien à la QDN

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/www#76]
bannière à mettre dans la barre latérale en haut, qui pointerait vers leur site de don:
https://soutien.laquadrature.net/

![Bannière](https://soutien.laquadrature.net/static/images/support_lqdn_250_B_fr.png)

**Comment by pascalchevrel** [comment]
Capture écran montrant la bannière une fois en place

![capture d ecran 2015-11-26 a 11 11 13](https://cloud.githubusercontent.com/assets/454375/11420553/238e4496-942f-11e5-8465-dec63992b45e.png)

**Comment by SphinxKnight** [comment]
:+1:

**Comment by fabienwang** [comment]
Super. Je l'intégrerais sur le nouveau site.
