### ISSUE TITLE
Nettoyage des liens dans la barre latérale

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/www#89]
Il y a un paquet de liens obsolètes ou 404, on va commencer par enlever tout ce qui est cassé avant de réfléchir à ce qu'on rajoutera.

**Comment by pascalchevrel** [comment]
Suppression nécessaire de : 
- diaspora (404)
- Firefox Android Apk (404)
- 'Autres' -> va vers frenchmozilla qu'on veut supprimer
- Bonjour Mozilla -> mort
- French Mozilla -> mort
- Toute la section "Communautés"

Ajouts nécessaires:
- Firefox pour iOS https://www.mozilla.org/fr/firefox/ios/?from=mozfr

Renommer "Activités" en 'Nos blogs thématiques"
- ajouter "Mozilla et la vie publique" https://notreinternet.mozfr.org/
-  ajouter "Firefox OS" https://firefoxos.mozfr.org/

S'assurer que l'on utilise toujours https pour nos pages mozfr

Ajouter une section "Sites officiels":
- mozilla.org -> https://www.mozilla.org/fr/
- Documentation utilisateurs -> https://support.mozilla.org/fr/
- Documentation développeurs -> https://developer.mozilla.org/fr/
- Modules et extensions -> https://addons.mozilla.org/fr/

**Comment by pascalchevrel** [comment]
La sidebar devrait aussi être un include twig

**Comment by Mozinet-fr** [comment]
J'avais proposé ça https://github.com/mozfr/www/pull/72 et Chris/Hello n'a pas eu le temps de se pencher dessus pour finir les modifications.

**Comment by fabienwang** [comment]
Vu à l'instant, le lien Diaspora n'est pas à virer:

https://github.com/mozfr/besogne/issues/58

**Comment by MatonAnthony** [comment]
Firefox Android ne renvoie plus vers une 404

**Comment by Flaburgan** [comment]
Le compte diaspora* est bien mort, je ne suis pas au courant si quelqu'un en à réouvert un (sur framasphere.org par exemple ?) https://github.com/mozfr/www/pull/106 s'est occupée de ca.
